  version: '3.3'

  volumes:
    postgres_data:
    static:
    media:
  services:
    db:
      image: postgres:13.1-alpine
      container_name: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      env_file:
        - ./.env
      restart: always
    web:
      image: donskihalexey/yamdb_final:latest
      restart: always
      volumes:
        - .:/code
        - static:/code/static/
      depends_on:
        - db
      env_file:
        - ./.env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/static/
    ports:
      - 9000:80
    depends_on:
      - web
